[package]
name    = "intellibiz-ledger"
version = "0.1.0"
edition = "2021"

[dependencies]
serde        = { workspace = true }
serde_json   = { workspace = true }
sha2         = { workspace = true }
ed25519-dalek = { workspace = true }
rust_decimal = { workspace = true }
crossbeam    = { workspace = true }
parking_lot  = { workspace = true }
tokio        = { workspace = true }
thiserror    = { workspace = true }
chrono       = { workspace = true }